trigger:
  branches:
    include: [main]

pool:
  name: onboarding-pool

steps:
- checkout: self
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/target/*.war'
    artifact: 'war'
